#FROM python:3.8-alpine3.14
FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    pip3 install --upgrade pip && \
    pip3 install --upgrade setuptools

WORKDIR /app

COPY requirements.txt .
COPY requirements-server.txt .
COPY main.py .
copy server.py .

RUN pip3 install -r requirements.txt && \
    pip3 install -r requirements-server.txt

ARG port=8080
ARG project=testvyos
ARG region=europe-west1
ENV PORT=${port}
ENV PROJECT=${project}
ENV REGION=${region}

ENTRYPOINT gunicorn --bind :$PORT --workers 1 --threads 1 --timeout 0 server:app